### ISSUE TITLE
compare results after using sqrt

### ISSUE THREAD

**Issue by cd155** [cd155/haskell-leetcode#3]
https://github.com/cd155/haskell-leetcode/blob/dac5f79a211af32cedb78ffbe4735faad25cab76/main/WeekThree.hs#L153-L159

Hi @balacij, do you know what if I change the `xsWithDist` to the following code?
```haskell
where xsWithDist = map (\(x,y) -> ((x,y), sqrt $ fromIntegral (x^2 + y^2))) xs 
```
It starts giving me a type error because the `sqrt` return a `Floating a` type. Is there a way to convert `Floating a` to `Int`? I can use `round`, but it will return the nearest integer, which is useless in this case. The result of `Floating a` is the distance between the (0,0) to its coordinates, so I think it would be better to have some decimals.

**Comment by balacij** [comment]
Maybe it would be best to change the return type of kClosetAux to return a `[(Coord, Float)]` instead?

You can convert a float to an integer in Haskell, but as you mention, you have to either ceil or truncate, so if you need the decimals, it might be best to just change the expectation of the value instead of the value itself to fit.

**Comment by cd155** [comment]
@balacij, the default method for `ceil` and `truncate` all return the nearest integer. If I need a number with some decimals, for example, 3.1415926, it will be either 3 or 4.

I can try multiple 3.1415926 * 10^7, then use `ceil` or `truncate`, then `/` it by 10^7, that will give a number I need. I feel the method is a little bit cumbersome. Any suggestion to improve it?

**Comment by balacij** [comment]
Oh, so you have a number of significant digits then?

**Comment by cd155** [comment]
I think I got confused with `Floating a` and `Float`. Changing the type to `Float` is indeed the right thing to do. Then I can just compare with sorting the list base on floats.

https://github.com/cd155/haskell-leetcode/blob/702ca69fb3527e669691065a3e78e8e49c0a5c5e/main/WeekThree.hs#L155-L158

**Comment by balacij** [comment]
Oh, perfect! :)
